### ISSUE TITLE
合并后的问题..

### ISSUE THREAD

**Issue by jjeejj** [game-helper/hongbao#20]
你这合并的有点仓促啊，服务还是分开的,应该这个项目就是一个服务。

**Comment by jjeejj** [comment]
![wx20180226-182900](https://user-images.githubusercontent.com/15176971/36665603-ff89bfc6-1b22-11e8-8dab-d9669f000406.png)
你要是没空， 我fork一下 。给你合并改改呀

**Comment by zhuweiyou** [comment]
服务在一块的。

客户端打算 完全分离开发，先放着，可能以后还有 小程序 之类的客户端

**Comment by zhuweiyou** [comment]
刚拿 Vue 重构了哦，如果你有兴趣优化页面的话，也欢迎

**Comment by CPK1021** [comment]
大佬问下rohr.js这个文件的作用是什么，里面的代码是压缩过了吗

**Comment by zhuweiyou** [comment]
@CPK1021  是美团网站的代码，混淆过的。只是调用它的方法而已，不用管它如何实现的。

**Comment by CPK1021** [comment]
好奇楼主怎么获得这些的

**Comment by zhuweiyou** [comment]
抓包

**Comment by zhuweiyou** [comment]
关了哦，看参考 首页 readme 目录说明
