### ISSUE TITLE
合并很快乐！

### ISSUE THREAD

**Issue by MAYBreath** [game-helper/hongbao#21]
之前不是说美团没法实现在线服务吗。。
因为有验证什么的。
看来没有大佬实现不了的事！
能否说下为什么现在美团也可以在线服务了。。

**Comment by zhuweiyou** [comment]
伪造的微信号，美团没有做验证，所以可以……

**Comment by MAYBreath** [comment]
666！强无敌！

**Comment by MAYBreath** [comment]
领美团红包的时候 有时候会显示：
message:write EPROTO 101057795:error:1409441B:SSL routines:ssl3_read_bytes:tlsv1 alert decrypt error:openssl\\ssl\\s3_pkt.c:1500:SSL alert number 51
101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\\ssl\\s3_pkt.c:659:

然后重新再领一次就正常了。

然后就是希望领取美团红包的时候，如果领取到了能显示自己的手机号，因为名字都是虚拟的话，不知道是不是真的被自己领了。。虚拟名字希望给系统用就好，领取到的话 还是希望能显示自己的手机 这样的。。

**Comment by zhuweiyou** [comment]
那个应该是美团返回的。

名字这个美团可以改，饿了么的改不了。其实只要看到 “刚刚领取” 一般是领到了，如果是 N 分钟之前领取，说明这个包被别人领了。

**Comment by CPK1021** [comment]
大佬好叼 研究下源码

**Comment by zhuweiyou** [comment]
美团应该加好了 @MAYBreath 我暂时没链接测，应该OK

**Comment by zhuweiyou** [comment]
![image](https://user-images.githubusercontent.com/8413791/36708308-6755025c-1bad-11e8-8772-971cb4ed9311.png)

**Comment by MAYBreath** [comment]
OK，我测试下。
有时候美团也会显示message:socket hang up
但是重新试几次就可以，可能和饿了么一样需要重新连接。

PS原来大佬也是jquery派 开心，哈哈。我感觉js库实在太多了。。感觉天天有新技术，但是还是jquery用着顺手啊

**Comment by zhuweiyou** [comment]
不好意思 已经重构成 Vue 了

**Comment by MAYBreath** [comment]
用Vue了....o(╥﹏╥)o  晴....天霹雳。。


手机号测试OK了，这下很清楚了~
