### ISSUE TITLE
老哥  被机器人领了

### ISSUE THREAD

**Issue by Bookjun** [game-helper/hongbao#22]
https://activity.waimai.meituan.com/coupon/sharechannel/B2EA8E1ABA8B47EA82DB475BA17B517D?urlKey=6D62AF7BA4174193B1E9CA658AB1F00A

**Comment by zhuweiyou** [comment]
目前的机制是 `最佳是第几个 - 接口返回的数组个数 === 1` 来决定用大号领取

有可能领取速度太快了，美团查询时返回的数组不是最新内容，导致判断出错，认为还没到最佳，就用小号领掉了。

大部分情况都能领到，所以暂时不打算做 timeout 来延迟领取，再换个红包链接试试吧。

**Comment by tuzhis** [comment]
这种情况是，有时候美团会返回领取成功，但是领取数组内并没有包含这个刚刚领取的用户，所以对于这种情况领取人得+1

**Comment by zhuweiyou** [comment]
@tuzhis 

没有包含这个 “刚刚领取” 也有可能是其它情况领取失败，这个时候 + 1 就不对了。

**Comment by shiyagn** [comment]
老哥 啥时候可以修复这个bug

**Comment by shiyagn** [comment]
111

**Comment by zhuweiyou** [comment]
请移步新版 https://github.com/game-helper/hongbao2

旧版的逻辑不再更新
