### ISSUE TITLE
确实帮我领了,但是最佳不是我,很尴尬!

### ISSUE THREAD

**Issue by shenguanjiejie** [game-helper/hongbao#30]
![img_de363d621cca-1](https://user-images.githubusercontent.com/9425605/36880015-7f600616-1e01-11e8-8877-fe590d8d67b7.jpeg)

**Comment by zhuweiyou** [comment]
？自己关闭了，领到了么。

饿了么因为只有 10 个内置 QQ 账号，所以用的人多的时候，确实会被别人领掉。
