### ISSUE TITLE
10次里9次都被机器人领了

### ISSUE THREAD

**Issue by chenjiangui** [game-helper/hongbao#32]
老哥,rt

**Comment by sunchenguang** [comment]
被机器人误领的概率很大，不是高峰期还是经常误领

**Comment by zhuweiyou** [comment]
@sunchenguang  你确定是机器人领的，还是被别人先领掉了？

脚本会先用几个小号，把小红包领了。判断到下一个是最大红包时，更换大号绑定 qq，去领取。

网站每天几万人用，我们 qq 号只有几十个，当换你的大号时，刚好这个 qq 当做别人的小号又绑了一下子，然后调用领取就被小号领了。

**Comment by sunchenguang** [comment]
所以是我用大号绑定手机号后，别人用相同的sns绑定了随机的手机号，然后我的大号执行领红包时，就会变成别人的机器号领了？
但是
```
    const {data: {promotion_records = []}} = await request.post(`/restapi/marketing/promotion/weixin/${sns.openid}`, {
      device_id: '',
      group_sn: query.sn,
      hardware_id: '',
      method: 'phone',
      phone,
      platform: query.platform,
      sign: sns.eleme_key,
      track_id: '',
      unionid: 'fuck', // 别问为什么传 fuck，饿了么前端就是这么传的
      weixin_avatar: '',
      weixin_username: ''
    })
```
这里参数不是传了phone，代表大号，没用？
思路对吗？

**Comment by zhuweiyou** [comment]
@sunchenguang  对。

> 这里参数不是传了phone，代表大号，没用？

因为这是两个请求（绑定、领取），是分开的。
如果中途有人插进来，绑定你的号、（插进来 绑定小号）、领取。就被小号领掉了。

当然有办法可以解决这个问题，比如做 cookie 锁定，不被其它人绑等。目前还没做这方面的优化。

**Comment by zhuweiyou** [comment]
一定程度上减少了被小号领取的几率 https://github.com/game-helper/hongbao/pull/37

**Comment by zhuweiyou** [comment]
请移步新版 https://github.com/game-helper/hongbao2

旧版的逻辑不再更新
