### ISSUE TITLE
有毒？

### ISSUE THREAD

**Issue by zhuangzhuang** [game-helper/hongbao#33]
win10上  chrome下载 zip包报毒

**Comment by zhuweiyou** [comment]
代码都是开源的，有没有毒，你心里没数吗？

**Comment by MAYBreath** [comment]
我特别反感这种2货标题，有没有毒你不会先去自己查看看？两个有毒2字让作者看着多刺眼你知道吗？连开源的都说有毒，我怕你根本不适合来开源社区，哪里来回哪里去吧。
