### ISSUE TITLE
美团红包无法领取，什么时候可以修复好呢？

### ISSUE THREAD

**Issue by taoxincool** [game-helper/hongbao#35]
美团红包无法领取，什么时候可以修复好呢？

**Comment by suyuanhxx** [comment]
道高一尺，魔高一丈，哈哈哈

**Comment by zhuweiyou** [comment]
美团增加了 openid 的校验，短时间无法修复，需要研究其它方法哦。

**Comment by hobmgcode** [comment]
这种东西 就不能开源 浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪浪

**Comment by zhuweiyou** [comment]
重新分析了一下。

美团实际上是换了 AES Key，在服务端加密后 Set-Cookie: 密文的。

所以现在无法获得正确的 Key，不能像之前的代码，伪造明文再加密回去。

**Comment by imyip** [comment]
所以自用的话,openid伪造还是可以的?

**Comment by zhuweiyou** [comment]
@imyip  没错

**Comment by imyip** [comment]
@zhuweiyou 申请十来个小号,然后获取到oepnid就存起来...哈

**Comment by lhwu** [comment]
这样子弄，每天一个号领取红包次数有限制的，还是行不通啊

**Comment by zhuweiyou** [comment]
@lhwu  饿了么次数限制是跟着手机号走，你可以看我们的代码，目前饿了么只有十几个账号，支撑每天上万人使用

**Comment by zhuweiyou** [comment]
@imyip  是这样，能满足你自己使用。不要公开就行

**Comment by zhuweiyou** [comment]
@lhwu 一天五个红包不够你点外卖的吗

**Comment by lxz666** [comment]
怎么用美团啊

**Comment by zhuweiyou** [comment]
已失效 https://github.com/game-helper/hongbao/issues/45
